"""build_readme.py - writes README.md with every number taken from results.json"""
import json
import os
from pathlib import Path
ROOT = Path(__file__).resolve().parent
USER = os.environ.get("GITHUB_USER", "YOUR-GITHUB-USERNAME")
REPO = "patient-statement-ab-test"
r = json.loads((ROOT / "results.json").read_text())
d, res, unp, dis, bc = r["days"], r["resolution_30d"], r["unpaid"], r["dispute"], r["business_case"]
p = lambda x: "< 0.001" if x < 0.001 else f"{x:.3f}"
pc = lambda x: f"{100*x:.2f}%"
n_s, n_p = sum(r["n_statements"].values()), sum(r["n_patients"].values())

readme = f"""# Patient Statement Redesign: A/B Test Simulation

[![pipeline](https://github.com/{USER}/{REPO}/actions/workflows/ci.yml/badge.svg)](https://github.com/{USER}/{REPO}/actions/workflows/ci.yml)

**Live dashboard:** https://{USER}.github.io/{REPO}/

**Author:** Mokshith Talari, Senior Business Analyst
**Stack:** Python (pandas, NumPy, SciPy, matplotlib, seaborn), Jupyter, Chart.js
**Data:** 100% synthetic. No client, employer, payer, or patient data is used.

> This is a portfolio case study. The dataset is generated by `generate_dataset.py` and the treatment
> effects are simulation parameters, so the analysis *recovers* effects that were designed in. The point
> is the method: experiment design, validity checks, hypothesis testing, and an executive readout.

## Deliverables

| File | What it is |
|---|---|
| `index.html` | Interactive executive dashboard (open in a browser) |
| `figures/executive_summary_infographic.png` | One-slide executive summary |
| `patient_billing_ab_test.ipynb` | Executed notebook: design, checks, results, limitations |
| `PRD.md` | Requirements: hypothesis, metrics, guardrails, data dictionary |
| `tests/` + `.github/workflows/ci.yml` | CI rebuilds every artifact and runs integrity tests on each push |

## Experiment design

| Element | Choice |
|---|---|
| Intervention | Plain-language statement + QR mobile payment + 3-click payment plan |
| Unit of randomization | Patient ({n_p:,} patients, {n_s:,} statements); no patient appears in both arms |
| Primary metric | Days from statement to settlement (paid statements) |
| Secondary | Paid within 30 days; unpaid at 120 days; QR/mobile share of paid statements |
| Guardrail | Dispute rate must not increase |
| Power | ~2,300 statements/arm detects a 1.2-day difference (SD ~14.5, alpha 0.05, power 0.80) |

## Results (simulated)

| Metric | Control | Treatment | Difference | p-value |
|---|---|---|---|---|
| Sample ratio (patients) | {r['n_patients']['Control']:,} | {r['n_patients']['Treatment']:,} | 50/50 check | {p(r['srm']['p'])} (pass) |
| Pre-treatment balance | ${r['balance_check']['mean']['Control']:.2f} | ${r['balance_check']['mean']['Treatment']:.2f} | n.s. | {p(r['balance_check']['p'])} |
| **Days to pay (primary)** | {d['mean']['Control']:.2f} | {d['mean']['Treatment']:.2f} | **-{d['diff']:.2f} d** (95% CI {d['ci'][0]:.2f} to {d['ci'][1]:.2f}) | {p(d['p'])} |
| Days to pay, patient-level | | | -{d['patient_level']['diff']:.2f} d | {p(d['patient_level']['p'])} |
| Paid within 30 days | {pc(res['rate']['Control'])} | {pc(res['rate']['Treatment'])} | {res['diff_pp']:+.2f} pp | {p(res['p'])} |
| Unpaid at 120 days | {pc(unp['rate']['Control'])} | {pc(unp['rate']['Treatment'])} | {unp['diff_pp']:+.2f} pp | {p(unp['p'])} |
| Dispute rate (guardrail) | {pc(dis['rate']['Control'])} | {pc(dis['rate']['Treatment'])} | {dis['diff_pp']:+.2f} pp | {p(dis['p'])} (not worse) |
| QR/mobile share (paid) | {r['channel_share']['Control']['QR_Portal']:.1f}% | {r['channel_share']['Treatment']['QR_Portal']:.1f}% | | |

Tests: Welch's t-test (primary), Welch on patient-level means (clustering robustness), Mann-Whitney U
(skew robustness), two-proportion z-tests (rates), chi-square (sample ratio, age balance).

## Illustrative business case

Scenario assumptions (editable in `run_analysis.py`): {bc['annual_statement_volume']:,} statements/year,
{bc['cost_of_capital']:.0%} cost of capital. These are **not additive**.

| Component | Type | Value |
|---|---|---|
| Cash collected earlier | One-time | ${bc['one_time_cash_acceleration']:,.0f} |
| Carrying-cost saving on that cash | Annual | ${bc['annual_carrying_cost_saving']:,.0f} |
| Balances no longer unpaid at 120 days (gross, before collection costs) | Annual | ${bc['annual_balances_no_longer_unpaid']:,.0f} |

## Limitations

- Effects are designed into the simulation; real results would be smaller and noisier.
- The treatment bundles three changes; a factorial follow-up would isolate each.
- Dropping unpaid statements from the days-to-pay mean ignores censoring; a survival model is the production-grade approach.

## Reproduce

```bash
pip install -r requirements.txt
python generate_dataset.py          # synthetic data (seeded, reproducible)
python run_analysis.py              # tests, figures, results.json
python generate_executive_infographic.py
python build_dashboard.py            # index.html from results.json
python create_notebook.py           # executed notebook
python build_readme.py              # this README
pytest -q                           # integrity tests
```

Every number in the dashboard, infographic, notebook, and README is read from `results.json`; none is typed by hand.
"""
(ROOT / "README.md").write_text(readme, encoding="utf-8")
print("Wrote README.md")
