"""create_notebook.py - builds and executes patient_billing_ab_test.ipynb"""
from pathlib import Path
import nbformat as nbf
from nbconvert.preprocessors import ExecutePreprocessor

ROOT = Path(__file__).resolve().parent
md, code = nbf.v4.new_markdown_cell, nbf.v4.new_code_cell
nb = nbf.v4.new_notebook()
nb.cells = [
    md("# Patient Statement Redesign: A/B Test Simulation\n"
       "**Author:** Mokshith Talari  \n"
       "**Data:** 100% synthetic, generated by `generate_dataset.py`. Treatment effects are simulation "
       "parameters; this notebook demonstrates method, not a real-world result."),
    md("## 1. Design\n"
       "- **Hypothesis:** a plain-language statement with a QR payment link and payment-plan option reduces days to pay.\n"
       "- **Unit of randomization:** patient (all of a patient's statements get the same template).\n"
       "- **Primary metric:** days from statement to settlement (paid statements).\n"
       "- **Secondary:** paid within 30 days; unpaid at 120 days; QR/mobile share.\n"
       "- **Guardrail:** dispute rate must not increase.\n"
       "- **Power:** to detect a 1.2-day difference with SD about 14.5, alpha 0.05 (two-sided), power 0.80, "
       "about 2,300 statements per arm are needed; this design is well powered."),
    code("import json, pandas as pd\n"
         "from run_analysis import analyze, report\n"
         "df = pd.read_csv('data/patient_billing_cohorts.csv')\n"
         "df.head()"),
    md("## 2. Validity checks, primary and secondary results"),
    code("r = analyze(df)\nreport(r)"),
    md("## 3. Subgroups (days faster, control minus treatment)"),
    code("pd.DataFrame({'by age': r['age_days_delta']}).join(pd.Series(r['tier_days_delta'], name='by balance tier'), how='outer')"),
    md("## 4. Figures"),
    code("from IPython.display import Image, display\n"
         "for f in ['figure1_distribution_days_to_pay', 'figure2_resolution_rates_by_age',\n"
         "          'figure3_channel_shift', 'figure4_balance_tier_boxplot']:\n"
         "    display(Image(f'figures/{f}.png', width=750))"),
    md("## 5. Illustrative business case\n"
       "Assumptions live in `ASSUMPTIONS` in `run_analysis.py`. One-time cash acceleration and annual effects are "
       "reported separately and should not be summed."),
    code("pd.Series(r['business_case'])"),
    md("## 6. Recommendation and limitations\n"
       "- Results of this magnitude would satisfy the stated numerical decision thresholds; a production rollout decision would use inference aligned to the patient-level randomization. This simulation demonstrates the method and is not evidence for an actual rollout.\n"
       "- The primary test is statement-level; because randomization is by patient, a production analysis would make patient-level or clustered inference (cluster-robust SEs, GEE, or mixed models) primary.\n"
       "- The statement bundles three changes (layout, QR, payment plan); a follow-up factorial test would isolate each.\n"
       "- Real data would add seasonality, payer adjudication lag, and right-censoring; a survival model "
       "(Kaplan-Meier / Cox) would handle unpaid balances better than dropping them from the days-to-pay mean."),
]
ExecutePreprocessor(timeout=300, kernel_name="python3").preprocess(nb, {"metadata": {"path": str(ROOT)}})
nbf.write(nb, ROOT / "patient_billing_ab_test.ipynb")
print("Wrote and executed patient_billing_ab_test.ipynb")
